### ISSUE TITLE
Add ability to add custom log tag on cache requests

### ISSUE THREAD

**Issue by seanabraham** [uber/buck-http-cache#12]
In order to segment which requests to the http cache are coming from different machines (CI vs local machines for example) it would be helpful to be able to pass a tag to the buck-http-cache when making the GET request, perhaps as a query param or similar. I don't believe this is currently possible (no custom logging options appear in [this method](https://github.com/uber/buck-http-cache/blob/e97e08e7bae8d7bf88e9dbe29b928ee115bf485a/cache/src/main/java/com/uber/buckcache/resources/buckcache/BuckCacheResource.java#L85)) but correct me if I'm wrong. 

cc @zayhero @kageiit

**Comment by kageiit** [comment]
I believe you can pass in arbitrary headers in the cache request. One example is the cache expiry header. Using headers you should be able to log the type of requests at the frontend directly instead of making changes in the cache code itself

**Comment by seanabraham** [comment]
Good idea, especially paired with buck.cache.http_write_headers config option. I'll give it a try and report back if it works or not.

**Comment by kageiit** [comment]
Closing this since I assume @seanabraham has got it working by now :)
