### ISSUE TITLE
Memory usage grows past limit

### ISSUE THREAD

**Issue by andrewzhaosc** [uber/buck-http-cache#4]
and I get this warning in the logs

WARN  [2016-10-28 16:48:29,903] org.apache.ignite.internal.processors.cache.GridCacheProcessor: Off heap maximum memory configuration property will be ignored for the cache working in OFFHEAP_VALUES mode (memory usage will be unlimited): metadata. Consider configuring eviction policy or switching to OFFHEAP_TIERED mode or.

**Comment by dhaval2025** [comment]
@andrewzhaosc yea we have noticed that, unfortunately ignite does not respect the MAX Memory set in the configs when we are trying to store the values off_heap (we do this to avoid large GCs). 
So far we have been keeping the retention low (1-2 days) to avoid an OOM situation. 
We will try out the tiered mode and let you know how it is doing.

**Comment by andrewzhaosc** [comment]
I've been using tiered for a few days and it seems to work fine.  The memory usage metric doesn't display correctly though.
`^-- Non heap [used=13293MB, free=-1%, comm=74MB]`

Not sure if there is any performance impact, but it seems to work well enough

**Comment by dhaval2025** [comment]
nice .. I am going to try this out and update configs to use that .. if everything looks good.

**Comment by kageiit** [comment]
@dhaval2025 what was the result of the config change?

**Comment by dhaval2025** [comment]
@kageiit we tried it out in buck-staging .. looks all right .. i will be setting it on prod as well.

**Comment by kageiit** [comment]
Closing this as we have found a resolution already

**Comment by artem-zinnatullin** [comment]
Sorry guys, I don't see any commits/PRs related to `OFFHEAP_TIERED` change, how do you set this value? Thanks!
